//MONGODB CONNECTIONS
export const MOONGOOSE=""

//JWT SECRET AND EXPIRATION TIME
export const JWT_SECREET="8326823HWEFGBF83YR2CG2"
export const JWT_EXPIRATION_TIME=60*60*24*30;



//EMAIL SETTINGS
export const EMAIL_HOST=""
export const EMAIL_PORT=""
export const EMAIL__USER=""
export const EMAIL_PASSWORDS=""



//JSON SIZE AND URL CONFIG
export const JSON_MAX_SIZE="50MB"
export const URL_ENCODED=true



//REQUEST LIMITING SETTINGS
export const REQUEST_LIMIT_TIME= 15 * 60 * 1000; // 15 Min
export const REQUEST_LIMIT_NUMBER=3000; // Per 15 Min 3000 Request Allowed



//WEB CACHE CONFIG
export const WEB_CACHE=false



//SERVER PORT CONFIG
export const PORT=5050
